/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Packages */
        get: operations["searchPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorBody */
        ApiErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /**
             * Fielderrors
             * @description Present only for `validation`; keyed by dotted field path.
             */
            fieldErrors?: {
                [key: string]: string;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /**
         * Badge
         * @description Computed per departure by `services/catalog/pricing.badge_for` (04 §3).
         * @enum {string}
         */
        Badge: "filling-fast" | "sold-out" | "guaranteed";
        /** BadgeOption */
        BadgeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["Badge"];
        };
        /**
         * EnquiryType
         * @description The v1 subset of the `enquiry_type` DB enum (06 A1) — what the form can submit.
         *
         *     `callback`, `group` and `chat-handoff` are forward-compat DB values that join here with
         *     their features (v2 add-on / v3).
         * @enum {string}
         */
        EnquiryType: "standard" | "custom" | "contact";
        /** EnquiryTypeOption */
        EnquiryTypeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["EnquiryType"];
        };
        /**
         * ErrorCode
         * @description Mirrors `app.errors.ErrorCode` (the Literal the handlers use); a test keeps them equal.
         * @enum {string}
         */
        ErrorCode: "validation" | "unauthorized" | "forbidden" | "not_found" | "rate_limited" | "conflict" | "internal";
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Limits */
        Limits: {
            /**
             * Enquirymessagemax
             * @example 1000
             */
            enquiryMessageMax: number;
            /**
             * Imagemaxbytes
             * @example 5242880
             */
            imageMaxBytes: number;
            /**
             * Maxthemesperpackage
             * @example 3
             */
            maxThemesPerPackage: number;
            /**
             * Maxtravellers
             * @example 12
             */
            maxTravellers: number;
        };
        /** Meta */
        Meta: {
            /** Badges */
            badges: components["schemas"]["BadgeOption"][];
            /** Enquirytypes */
            enquiryTypes: components["schemas"]["EnquiryTypeOption"][];
            limits: components["schemas"]["Limits"];
            /** Themes */
            themes: components["schemas"]["ThemeOption"][];
        };
        /** PackageCard */
        PackageCard: {
            /** @description From the next upcoming departure */
            badge: components["schemas"]["Badge"] | null;
            /** Coverurl */
            coverUrl: string | null;
            /** Days */
            days: number;
            /**
             * Destination
             * @description Destination display name
             */
            destination: string;
            /** Highlights */
            highlights: string[];
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Slug */
            slug: string;
            /** Startingpricepaise */
            startingPricePaise: number;
            /** Themes */
            themes: components["schemas"]["Theme"][];
        };
        /** PackageList */
        PackageList: {
            /** Items */
            items: components["schemas"]["PackageCard"][];
            /** Total */
            total: number;
        };
        /**
         * Theme
         * @enum {string}
         */
        Theme: "beach" | "hills" | "honeymoon" | "family" | "adventure" | "heritage";
        /** ThemeOption */
        ThemeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["Theme"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    searchPackages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
