/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Route
         * @description Never cached: the owner refreshes this page to see the enquiry that just landed.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Route */
        get: operations["listAdminDestinations"];
        put?: never;
        /** Create Route */
        post: operations["createDestination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/destinations/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Cover Route
         * @description Multipart proxy (06 C3): validate + resize in a thread, then one Blob PUT.
         */
        post: operations["uploadDestinationCover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/destinations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["getAdminDestination"];
        /** Update Route */
        put: operations["updateDestination"];
        post?: never;
        /** Delete Route */
        delete: operations["deleteDestination"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/enquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Route */
        get: operations["listAdminEnquiries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/enquiries.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Route
         * @description Streamed, never stored: no Blob object to create and no garbage to collect.
         */
        get: operations["exportEnquiriesCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/enquiries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["getAdminEnquiry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/enquiries/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Note Route
         * @description 201 with the whole enquiry, not just the note: the client renders the fresh timeline.
         */
        post: operations["addEnquiryNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/enquiries/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Status Route */
        patch: operations["setEnquiryStatus"];
        trace?: never;
    };
    "/admin/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Route */
        get: operations["listAdminPackages"];
        put?: never;
        /** Create Route */
        post: operations["createPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/packages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["getAdminPackage"];
        /** Update Route */
        put: operations["updatePackage"];
        post?: never;
        /** Delete Route */
        delete: operations["deletePackage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/packages/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Route */
        post: operations["duplicatePackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/packages/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Route */
        post: operations["uploadPackageImage"];
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder Route */
        patch: operations["reorderPackageImages"];
        trace?: never;
    };
    "/admin/packages/{id}/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Route */
        delete: operations["deletePackageImage"];
        options?: never;
        head?: never;
        /** Alt Route */
        patch: operations["updatePackageImage"];
        trace?: never;
    };
    "/admin/packages/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Status Route */
        post: operations["setPackageStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Route */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Destinations */
        get: operations["listDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Destination Route */
        get: operations["getDestination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Enquiry */
        post: operations["submitEnquiry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Home Route */
        get: operations["getHomeData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Packages
         * @description R3 search. Every filter lives in `search_packages`; this only adds the cache header.
         */
        get: operations["searchPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package Route */
        get: operations["getPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{slug}/departures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Departures Route */
        get: operations["getDeparturesForMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{slug}/itinerary.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Itinerary Pdf */
        get: operations["getItineraryPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post View */
        post: operations["recordView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminDeparture
         * @description Every departure the owner has, past ones included; `seats_left` is read-only.
         */
        AdminDeparture: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Guaranteed */
            guaranteed: boolean;
            /** Id */
            id: string;
            /** Pricechildpaise */
            priceChildPaise: number;
            /** Pricedoublepaise */
            priceDoublePaise: number;
            /** Pricetriplepaise */
            priceTriplePaise: number;
            /**
             * Seatsleft
             * @description From the departure_availability view; never edited
             */
            seatsLeft: number;
            /** Seatstotal */
            seatsTotal: number;
            /** Singlesupplementpaise */
            singleSupplementPaise: number;
        };
        /**
         * AdminDestination
         * @description A destination row as the owner sees it — including ones the public list hides.
         */
        AdminDestination: {
            /** Bestmonths */
            bestMonths: number[];
            /** Coverurl */
            coverUrl: string;
            /** Id */
            id: string;
            /** Intro */
            intro: string;
            /** Livepackagecount */
            livePackageCount: number;
            /** Name */
            name: string;
            /**
             * Packagecount
             * @description All packages, draft or live
             */
            packageCount: number;
            /** Position */
            position: number;
            /** Region */
            region: string;
            /** Slug */
            slug: string;
            /**
             * Sluglocked
             * @description True once any package here has been published; the slug is then fixed
             */
            slugLocked: boolean;
            /** Tagline */
            tagline: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** AdminDestinationList */
        AdminDestinationList: {
            /** Items */
            items: components["schemas"]["AdminDestination"][];
        };
        /**
         * AdminEnquiry
         * @description Everything the visitor submitted, plus the timeline (A7).
         */
        AdminEnquiry: {
            /** Adults */
            adults: number;
            /**
             * Budgetpaise
             * @description Custom enquiries only; per person
             */
            budgetPaise: number | null;
            /**
             * Changes
             * @description Custom enquiries only
             */
            changes: string | null;
            /** Children */
            children: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Device
             * @description Derived from the user agent; no geo lookup exists
             * @enum {string}
             */
            device: "Mobile" | "Desktop" | "Unknown";
            /** Email */
            email: string;
            emailStatus: components["schemas"]["EmailStatus"];
            /** Id */
            id: string;
            /** Message */
            message: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes: components["schemas"]["EnquiryNoteOut"][];
            package: components["schemas"]["EnquiryPackage"] | null;
            /** Phone */
            phone: string;
            /**
             * Preferreddates
             * @description Custom enquiries only
             */
            preferredDates: string | null;
            /** Ref */
            ref: string;
            /** Related */
            related: components["schemas"]["RelatedEnquiry"][];
            status: components["schemas"]["EnquiryStatus"];
            /** Travelmonth */
            travelMonth: string | null;
            type: components["schemas"]["EnquiryType"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Useragent */
            userAgent: string | null;
        };
        /** AdminImage */
        AdminImage: {
            /** Alt */
            alt: string;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /** AdminPackage */
        AdminPackage: {
            /** Canpublish */
            canPublish: boolean;
            /** Coverimageid */
            coverImageId: string | null;
            /** Days */
            days: number;
            /** Departurecity */
            departureCity: string;
            /**
             * Departures
             * @description All departures, soonest first
             */
            departures: components["schemas"]["AdminDeparture"][];
            destination: components["schemas"]["DestinationRef"];
            /** Destinationid */
            destinationId: string;
            /**
             * Editedat
             * Format: date-time
             * @description Moves on form saves only; send it back as `expectedEditedAt`
             */
            editedAt: string;
            /**
             * Enquirycount
             * @description All time; blocks delete when above 0
             */
            enquiryCount: number;
            /** Exclusions */
            exclusions: string[];
            /** Faq */
            faq: components["schemas"]["FaqItem"][];
            /** Featured */
            featured: boolean;
            /** Highlights */
            highlights: string[];
            /** Hotels */
            hotels: components["schemas"]["HotelOut"][];
            /** Id */
            id: string;
            /**
             * Images
             * @description Gallery order
             */
            images: components["schemas"]["AdminImage"][];
            /** Inclusions */
            inclusions: string[];
            /** Itinerary */
            itinerary: components["schemas"]["ItineraryDayOut"][];
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Publishrules */
            publishRules: components["schemas"]["PublishRule"][];
            /** Slug */
            slug: string;
            /**
             * Sluglocked
             * @description True once the package has been published
             */
            slugLocked: boolean;
            /** Startingpricepaise */
            startingPricePaise: number;
            status: components["schemas"]["PackageStatus"];
            /** Summary */
            summary: string;
            /** Themes */
            themes: components["schemas"]["Theme"][];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** AdminPackageList */
        AdminPackageList: {
            /** Items */
            items: components["schemas"]["AdminPackageRow"][];
        };
        /** AdminPackageRow */
        AdminPackageRow: {
            /** Coverurl */
            coverUrl: string | null;
            /** Days */
            days: number;
            /**
             * Departurecount
             * @description Dated today or later
             */
            departureCount: number;
            destination: components["schemas"]["DestinationRef"];
            /** Featured */
            featured: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /**
             * Recentenquirycount
             * @description Enquiries in the last 30 days
             */
            recentEnquiryCount: number;
            /** Slug */
            slug: string;
            /** Startingpricepaise */
            startingPricePaise: number;
            status: components["schemas"]["PackageStatus"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ApiErrorBody */
        ApiErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /**
             * Fielderrors
             * @description Present only for `validation`; keyed by dotted field path.
             */
            fieldErrors?: {
                [key: string]: string;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /**
         * Badge
         * @description Computed per departure by `services/catalog/pricing.badge_for` (04 §3).
         * @enum {string}
         */
        Badge: "filling-fast" | "sold-out" | "guaranteed";
        /** BadgeOption */
        BadgeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["Badge"];
        };
        /** Body_uploadDestinationCover */
        Body_uploadDestinationCover: {
            /** File */
            file: string;
        };
        /** Body_uploadPackageImage */
        Body_uploadPackageImage: {
            /** File */
            file: string;
        };
        /** Dashboard */
        Dashboard: {
            /**
             * Awaitingfirstcall
             * @description Enquiries still at status `new`
             */
            awaitingFirstCall: number;
            byStatus: components["schemas"]["StatusCounts"];
            /**
             * Convertedlast30Days
             * @description Received in that window and now marked converted
             */
            convertedLast30Days: number;
            /**
             * Enquirieslast30Days
             * @description Received in the last 30 IST days
             */
            enquiriesLast30Days: number;
            /**
             * Enquirieslastweek
             * @description All seven days of last week
             */
            enquiriesLastWeek: number;
            /**
             * Enquirieslastweektodate
             * @description Last week up to the same weekday, so the delta compares like with like
             */
            enquiriesLastWeekToDate: number;
            /**
             * Enquiriesthisweek
             * @description Monday to now
             */
            enquiriesThisWeek: number;
            /**
             * Oldestnewat
             * @description Null when nothing is waiting
             */
            oldestNewAt: string | null;
            /**
             * Today
             * Format: date
             * @description The IST business day every window below is measured from
             */
            today: string;
            /** Topbyenquiries */
            topByEnquiries: components["schemas"]["PackageCount"][];
            /** Topbyviews */
            topByViews: components["schemas"]["PackageCount"][];
            /**
             * Upcomingdepartures
             * @description At most 20; `upcomingDeparturesTotal` is the real count
             */
            upcomingDepartures: components["schemas"]["UpcomingDeparture"][];
            /**
             * Upcomingdeparturestotal
             * @description Departures in the whole window
             */
            upcomingDeparturesTotal: number;
            /** Viewslast7Days */
            viewsLast7Days: number;
            /**
             * Viewsprevious7Days
             * @description The 7 days before those, for the delta
             */
            viewsPrevious7Days: number;
            /**
             * Weekstart
             * Format: date
             * @description Monday of the current IST week
             */
            weekStart: string;
            /**
             * Windowstart
             * Format: date
             * @description First day of the 30-day windows below
             */
            windowStart: string;
        };
        /**
         * DepartureInput
         * @description `id` present = update that row; absent = insert. Rows the payload omits are deleted.
         *
         *     Prices are `ge=0` so a draft can park a departure with the rate still to be agreed; the
         *     publish rules are what insist on real prices before the package can go live.
         */
        DepartureInput: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Guaranteed
             * @default false
             */
            guaranteed: boolean;
            /** Id */
            id?: string | null;
            /** Pricechildpaise */
            priceChildPaise: number;
            /** Pricedoublepaise */
            priceDoublePaise: number;
            /** Pricetriplepaise */
            priceTriplePaise: number;
            /** Seatstotal */
            seatsTotal: number;
            /** Singlesupplementpaise */
            singleSupplementPaise: number;
        };
        /** DepartureList */
        DepartureList: {
            /**
             * Items
             * @description Upcoming departures, soonest first
             */
            items: components["schemas"]["DepartureOut"][];
        };
        /** DepartureOut */
        DepartureOut: {
            badge: components["schemas"]["Badge"] | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Guaranteed */
            guaranteed: boolean;
            /** Id */
            id: string;
            /**
             * Pricechildpaise
             * @description Child 5-11 sharing the parents' room
             */
            priceChildPaise: number;
            /**
             * Pricedoublepaise
             * @description Per adult, double sharing
             */
            priceDoublePaise: number;
            /** Pricetriplepaise */
            priceTriplePaise: number;
            /**
             * Seatsleft
             * @description From the departure_availability view
             */
            seatsLeft: number;
            /** Seatstotal */
            seatsTotal: number;
            /** Singlesupplementpaise */
            singleSupplementPaise: number;
        };
        /** DestinationCard */
        DestinationCard: {
            /**
             * Bestmonths
             * @description 1-12, in the destination's display order
             */
            bestMonths: number[];
            /** Coverurl */
            coverUrl: string;
            /** Name */
            name: string;
            /**
             * Packagecount
             * @description Live packages
             */
            packageCount: number;
            /** Slug */
            slug: string;
            /** Startingpricepaise */
            startingPricePaise: number;
            /** Tagline */
            tagline: string;
        };
        /** DestinationDetail */
        DestinationDetail: {
            /**
             * Bestmonths
             * @description 1-12
             */
            bestMonths: number[];
            /** Coverurl */
            coverUrl: string;
            /**
             * Intro
             * @description Markdown
             */
            intro: string;
            /** Name */
            name: string;
            /**
             * Packages
             * @description Live packages, cheapest first
             */
            packages: components["schemas"]["PackageCard"][];
            /** Region */
            region: string;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline: string;
        };
        /**
         * DestinationInput
         * @description Owner create/update body (06 §A3). Months are de-duplicated and sorted.
         */
        DestinationInput: {
            /** Bestmonths */
            bestMonths: number[];
            /** Coverurl */
            coverUrl: string;
            /**
             * Intro
             * @description Markdown, 2–3 paragraphs
             */
            intro: string;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Region */
            region: string;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline: string;
        };
        /** DestinationList */
        DestinationList: {
            /**
             * Items
             * @description Only destinations with at least 1 live package
             */
            items: components["schemas"]["DestinationCard"][];
        };
        /** DestinationRef */
        DestinationRef: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * EmailStatus
         * @enum {string}
         */
        EmailStatus: "sent" | "failed" | "skipped";
        /** EnquiryCreate */
        EnquiryCreate: {
            /** Adults */
            adults: number;
            /**
             * Budget
             * @description Rupees per person on the wire; paise here
             */
            budget?: number | null;
            /** Changes */
            changes?: string | null;
            /**
             * Children
             * @default 0
             */
            children: number;
            /** Email */
            email: string;
            /** Message */
            message?: string | null;
            /** Name */
            name: string;
            /** Packageslug */
            packageSlug?: string | null;
            /** Phone */
            phone: string;
            /** Preferreddates */
            preferredDates?: string | null;
            /**
             * Travelmonth
             * @description First of the month
             */
            travelMonth?: string | null;
            type: components["schemas"]["EnquiryType"];
            /**
             * Website
             * @description Honeypot — humans never fill it
             * @default
             */
            website: string;
        };
        /** EnquiryCreated */
        EnquiryCreated: {
            /**
             * Emailed
             * @description A confirmation email reached the visitor's address
             * @default false
             */
            emailed: boolean;
            /** Firstname */
            firstName: string;
            package: components["schemas"]["PackageRef"] | null;
            /**
             * Ref
             * @example TS-7F3K2Q
             */
            ref: string;
        };
        /** EnquiryList */
        EnquiryList: {
            counts: components["schemas"]["StatusCounts"];
            /** Items */
            items: components["schemas"]["EnquiryRow"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /**
             * Total
             * @description Rows matching every filter, including status
             */
            total: number;
            /** Totalpages */
            totalPages: number;
        };
        /** EnquiryNoteInput */
        EnquiryNoteInput: {
            /** Body */
            body: string;
        };
        /**
         * EnquiryNoteOut
         * @description Append-only; no author column in v1 — the UI renders the signed-in owner.
         */
        EnquiryNoteOut: {
            /** Body */
            body: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Id */
            id: string;
        };
        /** EnquiryPackage */
        EnquiryPackage: {
            /** Coverurl */
            coverUrl: string | null;
            /** Days */
            days: number;
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Slug */
            slug: string;
            /** Startingpricepaise */
            startingPricePaise: number;
            status: components["schemas"]["PackageStatus"];
        };
        /**
         * EnquiryRow
         * @description One line of the A6 table.
         */
        EnquiryRow: {
            /** Adults */
            adults: number;
            /** Children */
            children: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            package: components["schemas"]["PackageRef"] | null;
            /** Phone */
            phone: string;
            /** Ref */
            ref: string;
            status: components["schemas"]["EnquiryStatus"];
            /**
             * Travelmonth
             * @description First of the month
             */
            travelMonth: string | null;
            type: components["schemas"]["EnquiryType"];
        };
        /**
         * EnquiryStatus
         * @enum {string}
         */
        EnquiryStatus: "new" | "contacted" | "converted" | "closed";
        /** EnquiryStatusInput */
        EnquiryStatusInput: {
            status: components["schemas"]["EnquiryStatus"];
        };
        /**
         * EnquiryType
         * @description The v1 subset of the `enquiry_type` DB enum (06 A1) — what the form can submit.
         *
         *     `callback`, `group` and `chat-handoff` are forward-compat DB values that join here with
         *     their features (v2 add-on / v3).
         * @enum {string}
         */
        EnquiryType: "standard" | "custom" | "contact";
        /** EnquiryTypeOption */
        EnquiryTypeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["EnquiryType"];
        };
        /**
         * ErrorCode
         * @description Mirrors `app.errors.ErrorCode` (the Literal the handlers use); a test keeps them equal.
         * @enum {string}
         */
        ErrorCode: "validation" | "unauthorized" | "forbidden" | "not_found" | "rate_limited" | "conflict" | "internal";
        /** FacetOption */
        FacetOption: {
            /**
             * Count
             * @description Live packages in the whole catalog (not the current filter)
             */
            count: number;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** FaqItem */
        FaqItem: {
            /** A */
            a: string;
            /** Q */
            q: string;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HomeData */
        HomeData: {
            /**
             * Destinations
             * @description Display order, at most 6
             */
            destinations: components["schemas"]["DestinationCard"][];
            /**
             * Packages
             * @description Featured first, then cheapest; at most 6
             */
            packages: components["schemas"]["PackageCard"][];
            stats: components["schemas"]["HomeStats"];
            /**
             * Testimonials
             * @description By position
             */
            testimonials: components["schemas"]["TestimonialOut"][];
        };
        /** HomeStats */
        HomeStats: {
            /**
             * Departures
             * @description Upcoming departures of live packages with seats left
             */
            departures: number;
            /**
             * Destinations
             * @description Destinations with at least 1 live package
             */
            destinations: number;
            /**
             * Packages
             * @description Live packages
             */
            packages: number;
        };
        /** HotelInput */
        HotelInput: {
            /** City */
            city: string;
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Stars */
            stars: number;
        };
        /** HotelOut */
        HotelOut: {
            /** City */
            city: string;
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Stars */
            stars: number;
        };
        /** ImageAltInput */
        ImageAltInput: {
            /** Alt */
            alt: string;
        };
        /**
         * ImageOrderInput
         * @description The whole gallery order in one call; `cover_id` must be one of `order`.
         */
        ImageOrderInput: {
            /** Coverid */
            coverId?: string | null;
            /** Order */
            order: string[];
        };
        /** ImageOut */
        ImageOut: {
            /** Alt */
            alt: string;
            /** Height */
            height: number;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /**
         * ItineraryDayInput
         * @description One day of the itinerary. `day_no` is the array index + 1 — never sent.
         */
        ItineraryDayInput: {
            /**
             * Description
             * @description Markdown
             */
            description: string;
            meals: components["schemas"]["Meals"];
            /** Stay */
            stay?: string | null;
            /** Title */
            title: string;
        };
        /** ItineraryDayOut */
        ItineraryDayOut: {
            /** Dayno */
            dayNo: number;
            /**
             * Description
             * @description Markdown
             */
            description: string;
            meals: components["schemas"]["Meals"];
            /**
             * Stay
             * @description Hotel / city for the night; null on the last day
             */
            stay: string | null;
            /** Title */
            title: string;
        };
        /** Limits */
        Limits: {
            /**
             * Enquirymessagemax
             * @example 1000
             */
            enquiryMessageMax: number;
            /**
             * Imagemaxbytes
             * @example 4194304
             */
            imageMaxBytes: number;
            /**
             * Maxthemesperpackage
             * @example 3
             */
            maxThemesPerPackage: number;
            /**
             * Maxtravellers
             * @example 12
             */
            maxTravellers: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Meals */
        Meals: {
            /** Breakfast */
            breakfast: boolean;
            /** Dinner */
            dinner: boolean;
            /** Lunch */
            lunch: boolean;
        };
        /** Meta */
        Meta: {
            /** Badges */
            badges: components["schemas"]["BadgeOption"][];
            /** Enquirytypes */
            enquiryTypes: components["schemas"]["EnquiryTypeOption"][];
            limits: components["schemas"]["Limits"];
            /** Themes */
            themes: components["schemas"]["ThemeOption"][];
        };
        /** PackageCard */
        PackageCard: {
            /** @description From the next upcoming departure with seats; sold-out only when all are full */
            badge: components["schemas"]["Badge"] | null;
            /** Coverurl */
            coverUrl: string | null;
            /** Days */
            days: number;
            /**
             * Destination
             * @description Destination display name
             */
            destination: string;
            /** Highlights */
            highlights: string[];
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Slug */
            slug: string;
            /** Startingpricepaise */
            startingPricePaise: number;
            /** Themes */
            themes: components["schemas"]["Theme"][];
        };
        /**
         * PackageCount
         * @description A bar in one of the two top-five lists (A2 `.bars`).
         */
        PackageCount: {
            /** Count */
            count: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** PackageDetail */
        PackageDetail: {
            cover: components["schemas"]["ImageOut"] | null;
            /** Days */
            days: number;
            /** Departurecity */
            departureCity: string;
            /**
             * Departures
             * @description Upcoming only, soonest first
             */
            departures: components["schemas"]["DepartureOut"][];
            destination: components["schemas"]["DestinationRef"];
            /** Exclusions */
            exclusions: string[];
            /** Faq */
            faq: components["schemas"]["FaqItem"][];
            /** Highlights */
            highlights: string[];
            /** Hotels */
            hotels: components["schemas"]["HotelOut"][];
            /**
             * Images
             * @description Gallery order; the cover is first
             */
            images: components["schemas"]["ImageOut"][];
            /** Inclusions */
            inclusions: string[];
            /** Itinerary */
            itinerary: components["schemas"]["ItineraryDayOut"][];
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /**
             * Related
             * @description Up to 3: same destination, then shared theme
             */
            related: components["schemas"]["PackageCard"][];
            /** Slug */
            slug: string;
            /**
             * Startingpricepaise
             * @description Cheapest upcoming double-sharing price; 0 if none
             */
            startingPricePaise: number;
            /** Summary */
            summary: string;
            /** Themes */
            themes: components["schemas"]["Theme"][];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * PackageInput
         * @description Owner create/update body (06 §C4) — the whole package in one transaction.
         *
         *     `status` is deliberately absent: publishing is `POST /admin/packages/{id}/status`, so a
         *     PUT can never bypass the publish rules. `days` is derived (`nights + 1`, the DB check
         *     constraint `days_is_nights_plus_one`).
         */
        PackageInput: {
            /**
             * Departurecity
             * @default Ex-Mumbai
             */
            departureCity: string;
            /** Departures */
            departures?: components["schemas"]["DepartureInput"][];
            /** Destinationid */
            destinationId: string;
            /** Exclusions */
            exclusions?: string[];
            /**
             * Expectededitedat
             * @description The `editedAt` the form loaded. On update, a package saved since then answers 409 instead of being overwritten; omitted, the check is skipped
             */
            expectedEditedAt?: string | null;
            /** Faq */
            faq?: components["schemas"]["FaqItem"][];
            /**
             * Featured
             * @default false
             */
            featured: boolean;
            /** Highlights */
            highlights?: string[];
            /** Hotels */
            hotels?: components["schemas"]["HotelInput"][];
            /** Inclusions */
            inclusions?: string[];
            /** Itinerary */
            itinerary?: components["schemas"]["ItineraryDayInput"][];
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Themes */
            themes?: components["schemas"]["Theme"][];
        };
        /** PackageList */
        PackageList: {
            facets: components["schemas"]["SearchFacets"];
            /** Items */
            items: components["schemas"]["PackageCard"][];
            /** Total */
            total: number;
        };
        /** PackageRef */
        PackageRef: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * PackageStatus
         * @enum {string}
         */
        PackageStatus: "draft" | "live";
        /** PackageStatusInput */
        PackageStatusInput: {
            status: components["schemas"]["PackageStatus"];
        };
        /**
         * PublishRule
         * @description One live-publish precondition, evaluated by the api so the UI never re-derives it.
         */
        PublishRule: {
            /** Detail */
            detail: string;
            /**
             * Key
             * @enum {string}
             */
            key: "images" | "itinerary" | "departures" | "prices";
            /** Label */
            label: string;
            /** Ok */
            ok: boolean;
        };
        /** RangeFacet */
        RangeFacet: {
            /** Max */
            max: number;
            /** Min */
            min: number;
        };
        /**
         * RelatedEnquiry
         * @description A7's "other enquiries · same phone" panel.
         */
        RelatedEnquiry: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Id */
            id: string;
            /** Packagename */
            packageName: string | null;
            /** Ref */
            ref: string;
            status: components["schemas"]["EnquiryStatus"];
        };
        /**
         * SearchFacets
         * @description What the filter panel offers — derived from the live catalog, never hard-coded.
         */
        SearchFacets: {
            /** @description Cheapest / priciest starting price in rupees, rounded out to 1,000; 0/0 if none */
            budget: components["schemas"]["RangeFacet"];
            /**
             * Destinations
             * @description value = slug; display order
             */
            destinations: components["schemas"]["FacetOption"][];
            /**
             * Months
             * @description value = YYYY-MM; upcoming months with a departure that has seats, soonest first
             */
            months: components["schemas"]["FacetOption"][];
            /** @description Shortest / longest live package; 0/0 when none */
            nights: components["schemas"]["RangeFacet"];
            /**
             * Themes
             * @description Every theme in enum order; count may be 0
             */
            themes: components["schemas"]["FacetOption"][];
        };
        /**
         * SessionInfo
         * @description What `GET /auth/session` returns; `newEnquiries` feeds the admin sidebar badge (F16).
         */
        SessionInfo: {
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /**
             * Newenquiries
             * @description Enquiries still in status `new`
             */
            newEnquiries: number;
            user: components["schemas"]["SessionUser"];
        };
        /** SessionUser */
        SessionUser: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "price-asc" | "price-desc" | "duration";
        /**
         * StatusCounts
         * @description Every status counted with the current filters applied **except** `status` itself, so
         *     "New 3" means new within the view the owner is looking at (A6 tabs).
         */
        StatusCounts: {
            /** All */
            all: number;
            /** Closed */
            closed: number;
            /** Contacted */
            contacted: number;
            /** Converted */
            converted: number;
            /** New */
            new: number;
        };
        /** TestimonialOut */
        TestimonialOut: {
            /** City */
            city: string;
            /** Name */
            name: string;
            /** Packagename */
            packageName: string | null;
            /**
             * Packageslug
             * @description Null when unlinked or the package is not live
             */
            packageSlug: string | null;
            /** Rating */
            rating: number;
            /** Text */
            text: string;
        };
        /**
         * Theme
         * @enum {string}
         */
        Theme: "beach" | "hills" | "honeymoon" | "family" | "adventure" | "heritage";
        /** ThemeOption */
        ThemeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["Theme"];
        };
        /** UpcomingDeparture */
        UpcomingDeparture: {
            /** @description `pricing.badge_for`, the same rule the public departure table shows */
            badge: components["schemas"]["Badge"] | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Guaranteed */
            guaranteed: boolean;
            /** Id */
            id: string;
            /** Packageid */
            packageId: string;
            /** Packagename */
            packageName: string;
            /** Packageslug */
            packageSlug: string;
            /**
             * Seatsleft
             * @description From the departure_availability view; never stored
             */
            seatsLeft: number;
            /** Seatstotal */
            seatsTotal: number;
        };
        /** UploadedImage */
        UploadedImage: {
            /** Height */
            height: number;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "owner" | "customer";
        /** ViewCreate */
        ViewCreate: {
            /** Slug */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listAdminDestinations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDestinationList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createDestination: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDestination"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    uploadDestinationCover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadDestinationCover"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedImage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getAdminDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDestination"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    updateDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDestination"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    deleteDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listAdminEnquiries: {
        parameters: {
            query?: {
                status?: components["schemas"]["EnquiryStatus"] | null;
                type?: components["schemas"]["EnquiryType"] | null;
                packageId?: string | null;
                /** @description Received on or after this IST day */
                from?: string | null;
                /** @description Received on or before this IST day */
                to?: string | null;
                /** @description Name or phone */
                q?: string | null;
                /** @description 1-based; ignored by the CSV */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnquiryList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    exportEnquiriesCsv: {
        parameters: {
            query?: {
                status?: components["schemas"]["EnquiryStatus"] | null;
                type?: components["schemas"]["EnquiryType"] | null;
                packageId?: string | null;
                /** @description Received on or after this IST day */
                from?: string | null;
                /** @description Received on or before this IST day */
                to?: string | null;
                /** @description Name or phone */
                q?: string | null;
                /** @description 1-based; ignored by the CSV */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The filtered inbox as CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getAdminEnquiry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnquiry"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    addEnquiryNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnquiryNoteInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnquiry"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    setEnquiryStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnquiryStatusInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEnquiry"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listAdminPackages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPackageList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    createPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPackage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getAdminPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPackage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    updatePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPackage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    deletePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    duplicatePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPackage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    uploadPackageImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadPackageImage"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminImage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    reorderPackageImages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageOrderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPackage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    deletePackageImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    updatePackageImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageAltInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminImage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    setPackageStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageStatusInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPackage"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listDestinations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDetail"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    submitEnquiry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnquiryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnquiryCreated"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getHomeData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeData"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    searchPackages: {
        parameters: {
            query?: {
                /** @description Destination slugs (≤ 20); any of */
                destination?: string[];
                /** @description Maximum starting price per person, in rupees */
                maxBudget?: number | null;
                nightsMin?: number | null;
                nightsMax?: number | null;
                /** @description Any of */
                themes?: components["schemas"]["Theme"][];
                /** @description YYYY-MM: packages with a departure that month that still has seats */
                month?: string | null;
                sort?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageDetail"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getDeparturesForMonth: {
        parameters: {
            query?: {
                /** @description YYYY-MM; omitted or blank = all upcoming */
                month?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartureList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getItineraryPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PDF (no Blob store) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Redirect to the cached PDF */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Any query string: redirect to the bare URL */
            308: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Draft or unknown package */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many downloads from this address */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    recordView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
