/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Destinations */
        get: operations["listDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Destination Route */
        get: operations["getDestination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Packages
         * @description R3 search. Every filter lives in `search_packages`; this only adds the cache header.
         */
        get: operations["searchPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package Route */
        get: operations["getPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{slug}/departures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Departures Route */
        get: operations["getDeparturesForMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorBody */
        ApiErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /**
             * Fielderrors
             * @description Present only for `validation`; keyed by dotted field path.
             */
            fieldErrors?: {
                [key: string]: string;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /**
         * Badge
         * @description Computed per departure by `services/catalog/pricing.badge_for` (04 §3).
         * @enum {string}
         */
        Badge: "filling-fast" | "sold-out" | "guaranteed";
        /** BadgeOption */
        BadgeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["Badge"];
        };
        /** DepartureList */
        DepartureList: {
            /**
             * Items
             * @description Upcoming departures, soonest first
             */
            items: components["schemas"]["DepartureOut"][];
        };
        /** DepartureOut */
        DepartureOut: {
            badge: components["schemas"]["Badge"] | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Guaranteed */
            guaranteed: boolean;
            /** Id */
            id: string;
            /**
             * Pricechildpaise
             * @description Child 5-11 sharing the parents' room
             */
            priceChildPaise: number;
            /**
             * Pricedoublepaise
             * @description Per adult, double sharing
             */
            priceDoublePaise: number;
            /** Pricetriplepaise */
            priceTriplePaise: number;
            /**
             * Seatsleft
             * @description From the departure_availability view
             */
            seatsLeft: number;
            /** Seatstotal */
            seatsTotal: number;
            /** Singlesupplementpaise */
            singleSupplementPaise: number;
        };
        /** DestinationCard */
        DestinationCard: {
            /** Coverurl */
            coverUrl: string;
            /** Name */
            name: string;
            /**
             * Packagecount
             * @description Live packages
             */
            packageCount: number;
            /** Slug */
            slug: string;
            /** Startingpricepaise */
            startingPricePaise: number;
            /** Tagline */
            tagline: string;
        };
        /** DestinationDetail */
        DestinationDetail: {
            /**
             * Bestmonths
             * @description 1-12
             */
            bestMonths: number[];
            /** Coverurl */
            coverUrl: string;
            /**
             * Intro
             * @description Markdown
             */
            intro: string;
            /** Name */
            name: string;
            /**
             * Packages
             * @description Live packages, cheapest first
             */
            packages: components["schemas"]["PackageCard"][];
            /** Region */
            region: string;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline: string;
        };
        /** DestinationList */
        DestinationList: {
            /**
             * Items
             * @description Only destinations with at least 1 live package
             */
            items: components["schemas"]["DestinationCard"][];
        };
        /** DestinationRef */
        DestinationRef: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * EnquiryType
         * @description The v1 subset of the `enquiry_type` DB enum (06 A1) — what the form can submit.
         *
         *     `callback`, `group` and `chat-handoff` are forward-compat DB values that join here with
         *     their features (v2 add-on / v3).
         * @enum {string}
         */
        EnquiryType: "standard" | "custom" | "contact";
        /** EnquiryTypeOption */
        EnquiryTypeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["EnquiryType"];
        };
        /**
         * ErrorCode
         * @description Mirrors `app.errors.ErrorCode` (the Literal the handlers use); a test keeps them equal.
         * @enum {string}
         */
        ErrorCode: "validation" | "unauthorized" | "forbidden" | "not_found" | "rate_limited" | "conflict" | "internal";
        /** FacetOption */
        FacetOption: {
            /**
             * Count
             * @description Live packages in the whole catalog (not the current filter)
             */
            count: number;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** FaqItem */
        FaqItem: {
            /** A */
            a: string;
            /** Q */
            q: string;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HotelOut */
        HotelOut: {
            /** City */
            city: string;
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Stars */
            stars: number;
        };
        /** ImageOut */
        ImageOut: {
            /** Alt */
            alt: string;
            /** Height */
            height: number;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /** ItineraryDayOut */
        ItineraryDayOut: {
            /** Dayno */
            dayNo: number;
            /**
             * Description
             * @description Markdown
             */
            description: string;
            meals: components["schemas"]["Meals"];
            /**
             * Stay
             * @description Hotel / city for the night; null on the last day
             */
            stay: string | null;
            /** Title */
            title: string;
        };
        /** Limits */
        Limits: {
            /**
             * Enquirymessagemax
             * @example 1000
             */
            enquiryMessageMax: number;
            /**
             * Imagemaxbytes
             * @example 5242880
             */
            imageMaxBytes: number;
            /**
             * Maxthemesperpackage
             * @example 3
             */
            maxThemesPerPackage: number;
            /**
             * Maxtravellers
             * @example 12
             */
            maxTravellers: number;
        };
        /** Meals */
        Meals: {
            /** Breakfast */
            breakfast: boolean;
            /** Dinner */
            dinner: boolean;
            /** Lunch */
            lunch: boolean;
        };
        /** Meta */
        Meta: {
            /** Badges */
            badges: components["schemas"]["BadgeOption"][];
            /** Enquirytypes */
            enquiryTypes: components["schemas"]["EnquiryTypeOption"][];
            limits: components["schemas"]["Limits"];
            /** Themes */
            themes: components["schemas"]["ThemeOption"][];
        };
        /** PackageCard */
        PackageCard: {
            /** @description From the next upcoming departure */
            badge: components["schemas"]["Badge"] | null;
            /** Coverurl */
            coverUrl: string | null;
            /** Days */
            days: number;
            /**
             * Destination
             * @description Destination display name
             */
            destination: string;
            /** Highlights */
            highlights: string[];
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /** Slug */
            slug: string;
            /** Startingpricepaise */
            startingPricePaise: number;
            /** Themes */
            themes: components["schemas"]["Theme"][];
        };
        /** PackageDetail */
        PackageDetail: {
            cover: components["schemas"]["ImageOut"] | null;
            /** Days */
            days: number;
            /** Departurecity */
            departureCity: string;
            /**
             * Departures
             * @description Upcoming only, soonest first
             */
            departures: components["schemas"]["DepartureOut"][];
            destination: components["schemas"]["DestinationRef"];
            /** Exclusions */
            exclusions: string[];
            /** Faq */
            faq: components["schemas"]["FaqItem"][];
            /** Highlights */
            highlights: string[];
            /** Hotels */
            hotels: components["schemas"]["HotelOut"][];
            /**
             * Images
             * @description Gallery order; the cover is first
             */
            images: components["schemas"]["ImageOut"][];
            /** Inclusions */
            inclusions: string[];
            /** Itinerary */
            itinerary: components["schemas"]["ItineraryDayOut"][];
            /** Name */
            name: string;
            /** Nights */
            nights: number;
            /**
             * Related
             * @description Up to 3: same destination, then shared theme
             */
            related: components["schemas"]["PackageCard"][];
            /** Slug */
            slug: string;
            /**
             * Startingpricepaise
             * @description Cheapest upcoming double-sharing price; 0 if none
             */
            startingPricePaise: number;
            /** Summary */
            summary: string;
            /** Themes */
            themes: components["schemas"]["Theme"][];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** PackageList */
        PackageList: {
            facets: components["schemas"]["SearchFacets"];
            /** Items */
            items: components["schemas"]["PackageCard"][];
            /** Total */
            total: number;
        };
        /** RangeFacet */
        RangeFacet: {
            /** Max */
            max: number;
            /** Min */
            min: number;
        };
        /**
         * SearchFacets
         * @description What the filter panel offers — derived from the live catalog, never hard-coded.
         */
        SearchFacets: {
            /** @description Cheapest / priciest starting price in rupees, rounded out to 1,000; 0/0 if none */
            budget: components["schemas"]["RangeFacet"];
            /**
             * Destinations
             * @description value = slug; display order
             */
            destinations: components["schemas"]["FacetOption"][];
            /**
             * Months
             * @description value = YYYY-MM; upcoming months with a departure that has seats, soonest first
             */
            months: components["schemas"]["FacetOption"][];
            /** @description Shortest / longest live package; 0/0 when none */
            nights: components["schemas"]["RangeFacet"];
            /**
             * Themes
             * @description Every theme in enum order; count may be 0
             */
            themes: components["schemas"]["FacetOption"][];
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "price-asc" | "price-desc" | "duration";
        /**
         * Theme
         * @enum {string}
         */
        Theme: "beach" | "hills" | "honeymoon" | "family" | "adventure" | "heritage";
        /** ThemeOption */
        ThemeOption: {
            /** Label */
            label: string;
            value: components["schemas"]["Theme"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDestinations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationDetail"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    searchPackages: {
        parameters: {
            query?: {
                /** @description Destination slugs (≤ 20); any of */
                destination?: string[];
                /** @description Maximum starting price per person, in rupees */
                maxBudget?: number | null;
                nightsMin?: number | null;
                nightsMax?: number | null;
                /** @description Any of */
                themes?: components["schemas"]["Theme"][];
                /** @description YYYY-MM: packages with a departure that month that still has seats */
                month?: string | null;
                sort?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageDetail"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getDeparturesForMonth: {
        parameters: {
            query?: {
                /** @description YYYY-MM; omitted or blank = all upcoming */
                month?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartureList"];
                };
            };
            /** @description Error envelope (06 C0) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
